In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr[3]

4

There are 2 method we can create arrays using numpy

1. A list
2. A tuple

In [7]:
a = ['MCA', 33, 54, 76, 99]
b = (1, 33, 54, 76, 99)

In [8]:
arr1 = np.array(a)
arr2 = np.array(b)

In [9]:
arr1

array(['MCA', '33', '54', '76', '99'], dtype='<U21')

In [10]:
arr2

array([ 1, 33, 54, 76, 99])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
type(arr2)

numpy.ndarray

## Dimensions in arrays

1. 0-D Array
2. 1-D Array
3. 2-D Array
4. 3-D Array


In [23]:
# 0 - D Array

np.array(33)

array(33)

In [22]:
# 1 - D Array

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [21]:
# 2 - D Array

np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 3 - D Array

np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## Assignments

1. Why we require Numpy? (Mention at least 4 points)
3. What is the difference between list, tuple, array?