### Assignment: List down all the advantaged of bagging and boosting

In [133]:
from google.colab import files
import pandas as pd
import warnings
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report
warnings.filterwarnings('ignore')

In [68]:
uploaded = files.upload()
filename = next(iter(uploaded))

Saving heart.csv to heart (2).csv


In [69]:
heart_df = pd.read_csv(filename)

In [70]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [71]:
heart_df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [72]:
heart_df.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [73]:
print("Number of Records: ", heart_df.shape[0])

Number of Records:  1025


In [74]:
print("Number of Records: ", heart_df.shape[1])

Number of Records:  14


#### Show summary of all Numerical Data

In [75]:
heart_df.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [76]:
heart_df.describe().T

count        mean        std    min    25%    50%    75%    max
age       1025.0   54.434146   9.072290   29.0   48.0   56.0   61.0   77.0
sex       1025.0    0.695610   0.460373    0.0    0.0    1.0    1.0    1.0
cp        1025.0    0.942439   1.029641    0.0    0.0    1.0    2.0    3.0
trestbps  1025.0  131.611707  17.516718   94.0  120.0  130.0  140.0  200.0
chol      1025.0  246.000000  51.592510  126.0  211.0  240.0  275.0  564.0
fbs       1025.0    0.149268   0.356527    0.0    0.0    0.0    0.0    1.0
restecg   1025.0    0.529756   0.527878    0.0    0.0    1.0    1.0    2.0
thalach   1025.0  149.114146  23.005724   71.0  132.0  152.0  166.0  202.0
exang     1025.0    0.336585   0.472772    0.0    0.0    0.0    1.0    1.0
oldpeak   1025.0    1.071512   1.175053    0.0    0.0    0.8    1.8    6.2
slope     1025.0    1.385366   0.617755    0.0    1.0    1.0    2.0    2.0
ca        1025.0    0.754146   1.030798    0.0    0.0    0.0    1.0    4.0
thal      1025.0    2.323902   0.620660    0.0    2.0    2.0    3.0    3.0
target    1025.0    0.513171   0.500070    0.0    0.0    1.0    1.0    1.0

#### Show summary of all Categorical Data

In [77]:
# heart_df.describe(include="object")
# Categorical data is not there in the dataset

#### Check Nan Values

In [78]:
heart_df.isna()

age    sex     cp  trestbps   chol    fbs  restecg  thalach  exang  \
0     False  False  False     False  False  False    False    False  False   
1     False  False  False     False  False  False    False    False  False   
2     False  False  False     False  False  False    False    False  False   
3     False  False  False     False  False  False    False    False  False   
4     False  False  False     False  False  False    False    False  False   
...     ...    ...    ...       ...    ...    ...      ...      ...    ...   
1020  False  False  False     False  False  False    False    False  False   
1021  False  False  False     False  False  False    False    False  False   
1022  False  False  False     False  False  False    False    False  False   
1023  False  False  False     False  False  False    False    False  False   
1024  False  False  False     False  False  False    False    False  False   

      oldpeak  slope     ca   thal  target  
0       False  False  False  False   False  
1       False  False  False  False   False  
2       False  False  False  False   False  
3       False  False  False  False   False  
4       False  False  False  False   False  
...       ...    ...    ...    ...     ...  
1020    False  False  False  False   False  
1021    False  False  False  False   False  
1022    False  False  False  False   False  
1023    False  False  False  False   False  
1024    False  False  False  False   False  

[1025 rows x 14 columns]

In [79]:
heart_df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

#### Check Duplicates Records

In [80]:
heart_df.duplicated().sum()

np.int64(723)

In [81]:
heart_df = heart_df.drop_duplicates()

In [83]:
heart_df.duplicated().sum()

np.int64(0)

In [82]:
heart_df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0      1.0   
1     53    1   0       140   203    1        0      155      1      3.1   
2     70    1   0       145   174    0        1      125      1      2.6   
3     61    1   0       148   203    0        1      161      0      0.0   
4     62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0      1.5   
733   44    0   2       108   141    0        1      175      0      0.6   
739   52    1   0       128   255    0        1      161      1      0.0   
843   59    1   3       160   273    0        0      125      0      0.0   
878   54    1   0       120   188    0        1      113      0      1.4   

     slope  ca  thal  target  
0        2   2     3       0  
1        0   0     3       0  
2        0   0     3       0  
3        2   1     3       0  
4        1   3     2       0  
..     ...  ..   ...     ...  
723      1   0     2       1  
733      1   0     2       1  
739      2   1     3       0  
843      2   0     2       0  
878      1   1     3       0  

[302 rows x 14 columns]

#### Perform Categorical Data Encoding

In [84]:
# We dont have any categorical data

#### Splittig Data intp Train and Test

In [92]:
X = heart_df.drop(columns=["target"], axis=1)
y = heart_df.target

In [93]:
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0      1.0   
1     53    1   0       140   203    1        0      155      1      3.1   
2     70    1   0       145   174    0        1      125      1      2.6   
3     61    1   0       148   203    0        1      161      0      0.0   
4     62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0      1.5   
733   44    0   2       108   141    0        1      175      0      0.6   
739   52    1   0       128   255    0        1      161      1      0.0   
843   59    1   3       160   273    0        0      125      0      0.0   
878   54    1   0       120   188    0        1      113      0      1.4   

     slope  ca  thal  
0        2   2     3  
1        0   0     3  
2        0   0     3  
3        2   1     3  
4        1   3     2  
..     ...  ..   ...  
723      1   0     2  
733      1   0     2  
739      2   1     3  
843      2   0     2  
878      1   1     3  

[302 rows x 13 columns]

In [94]:
y

0      0
1      0
2      0
3      0
4      0
      ..
723    1
733    1
739    0
843    0
878    0
Name: target, Length: 302, dtype: int64

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#### Create Bagging Classifier Model

In [109]:
bagging_model1 = BaggingClassifier(estimator= SVC(), n_estimators=100, oob_score=True, max_samples=0.8, random_state=42)

In [110]:
bagging_model1

BaggingClassifier(estimator=SVC(), max_samples=0.8, n_estimators=100,
                  oob_score=True, random_state=42)

In [111]:
bagging_model1.fit(X_train, y_train)

BaggingClassifier(estimator=SVC(), max_samples=0.8, n_estimators=100,
                  oob_score=True, random_state=42)

In [112]:
bagging_model1.oob_score_

0.6303317535545023

#### Perform Hyperparameter Tuning

In [113]:
bagging_model2 = BaggingClassifier(estimator= DecisionTreeClassifier(), n_estimators=100, oob_score=True, max_samples=0.8, random_state=42)

In [114]:
bagging_model2.fit(X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, oob_score=True, random_state=42)

In [115]:
bagging_model2.oob_score_

0.8056872037914692

#### Compare the accuracy of Standalone Classifier and Bagging Classifier

In [125]:
model3 = DecisionTreeClassifier()

In [126]:
model3.fit(X_train, y_train)

DecisionTreeClassifier()

In [127]:
y_pred1 = model3.predict(X_test)

In [128]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.74      0.73      0.74        48
           1       0.70      0.72      0.71        43

    accuracy                           0.73        91
   macro avg       0.72      0.73      0.72        91
weighted avg       0.73      0.73      0.73        91



In [129]:
model4 = SVC(kernel='rbf')

In [130]:
model4.fit(X_train, y_train)

SVC()

In [131]:
y_pred2 = model4.predict(X_test)

In [132]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.79      0.23      0.35        48
           1       0.52      0.93      0.67        43

    accuracy                           0.56        91
   macro avg       0.65      0.58      0.51        91
weighted avg       0.66      0.56      0.50        91



In [167]:
score1 = cross_val_score(bagging_model1, X, y, cv=5)

In [168]:
score1

array([0.6557377 , 0.60655738, 0.7       , 0.63333333, 0.65      ])

In [169]:
score1.mean()

np.float64(0.6491256830601093)

In [144]:
score2 = cross_val_score(bagging_model2, X, y, cv=5)

In [145]:
score2

array([0.83606557, 0.81967213, 0.9       , 0.8       , 0.76666667])

In [146]:
score2.mean()

np.float64(0.8244808743169398)

In [147]:
score3 = cross_val_score(model3, X, y, cv=5)

In [148]:
score3

array([0.78688525, 0.73770492, 0.81666667, 0.73333333, 0.73333333])

In [149]:
score3.mean()

np.float64(0.761584699453552)

In [150]:
score4 = cross_val_score(model4, X, y, cv=5)

In [151]:
score4

array([0.67213115, 0.60655738, 0.73333333, 0.61666667, 0.6       ])

In [152]:
score4.mean()

np.float64(0.6457377049180328)

In [173]:
mean_score1 = score1.mean()
mean_score2 = score2.mean()
mean_score3 = score3.mean()
mean_score4 = score4.mean()

data = {
    "Model": ["Bagging Model 1 (SVC)", "Bagging Model 2 (Tree)", "Model 3 (Tree)", "Model 4 (SVC)"],
    "Mean Score": [mean_score1, mean_score2, mean_score3, mean_score4]
}

In [174]:
comparison_df = pd.DataFrame(data)

In [175]:
comparison_df

Model  Mean Score
0   Bagging Model 1 (SVC)    0.649126
1  Bagging Model 2 (Tree)    0.824481
2          Model 3 (Tree)    0.761585
3           Model 4 (SVC)    0.645738