In [35]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [36]:
corpus = [
    "I love to eat pizza",
    "I love to eat burger",
    "I love to eat sushi",
    "I love to eat pasta",
    "I love to eat salad",
    "I love to eat chocolate",
    "I love to eat ice cream",
    "I love to eat tacos",
    "I love to eat sandwiches",
    "I love to eat steak",

    "I love to play cricket",
    "I love to play football",
    "I love to play basketball",
    "I love to play tennis",
    "I love to play volleyball",
    "I love to play chess",
    "I love to play badminton",
    "I love to play baseball",
    "I love to play rugby",
    "I love to play golf",

    "I love to watch movies",
    "I love to watch tv",
    "I love to watch documentaries",
    "I love to watch cartoons",
    "I love to watch sports",
    "I love to watch news",
    "I love to watch dramas",
    "I love to watch comedies",
    "I love to watch thrillers",
    "I love to watch animations",

    "I love to read books",
    "I love to read novels",
    "I love to read magazines",
    "I love to read newspapers",
    "I love to read comics",
    "I love to read blogs",
    "I love to read articles",
    "I love to read poetry",
    "I love to read stories",
    "I love to read essays",

    "I love to travel abroad",
    "I love to travel locally",
    "I love to travel by plane",
    "I love to travel by train",
    "I love to travel by car",
    "I love to travel with friends",
    "I love to travel alone",
    "I love to travel during holidays",
    "I love to travel for adventure",
    "I love to travel for relaxation",

    "I love to listen to music",
    "I love to listen to podcasts",
    "I love to listen to audiobooks",
    "I love to listen to the radio",
    "I love to listen to live concerts",
    "I love to listen to classical music",
    "I love to listen to rock music",
    "I love to listen to pop music",
    "I love to listen to jazz music",
    "I love to listen to electronic music",

    "I love to cook dinner",
    "I love to cook breakfast",
    "I love to cook lunch",
    "I love to cook desserts",
    "I love to cook Italian food",
    "I love to cook Chinese food",
    "I love to cook Indian food",
    "I love to cook Mexican food",
    "I love to cook vegan food",
    "I love to cook fast food",

    "I love to exercise daily",
    "I love to exercise in the morning",
    "I love to exercise at the gym",
    "I love to exercise outdoors",
    "I love to exercise with friends",
    "I love to exercise for health",
    "I love to exercise to lose weight",
    "I love to exercise to gain muscle",
    "I love to exercise for fun",
    "I love to exercise after work",

    "I love to learn new skills",
    "I love to learn languages",
    "I love to learn coding",
    "I love to learn cooking",
    "I love to learn painting",
    "I love to learn dancing",
    "I love to learn singing",
    "I love to learn photography",
    "I love to learn writing",
    "I love to learn public speaking",

    "I love to relax on weekends",
    "I love to relax at home",
    "I love to relax by the beach",
    "I love to relax in nature",
    "I love to relax with family",
    "I love to relax with pets",
    "I love to relax by reading",
    "I love to relax by watching tv",
    "I love to relax by listening to music",
    "I love to relax by meditating",

    "The quick brown fox jumps over the lazy dog",
    "She sells seashells by the seashore",
    "Can you pass me the salt please",
    "They went to the park yesterday",
    "I am learning how to play guitar",
    "We should meet for coffee tomorrow",
    "Do you like watching movies on weekends",
    "He is reading a fascinating book",
    "The weather today is surprisingly pleasant",
    "She cooked a delicious meal last night",

    "My cat loves to chase butterflies",
    "He runs faster than anyone else",
    "They built a new house by the lake",
    "Are you coming to the party later",
    "I forgot my keys at home",
    "The children are playing in the garden",
    "This painting is a masterpiece",
    "We traveled to Japan last summer",
    "Please turn off the lights when you leave",
    "She sings beautifully on stage",

    "The computer crashed during the presentation",
    "Can you help me with this problem",
    "He drives a red sports car",
    "They enjoy hiking in the mountains",
    "I will call you after the meeting",
    "The dog barked loudly at the stranger",
    "She is writing a letter to her friend",
    "We watched the sunset from the hilltop",
    "The flowers bloom in spring",
    "Do you prefer tea or coffee",

    "The baby is sleeping peacefully",
    "He studies hard for his exams",
    "They adopted a puppy from the shelter",
    "I like to listen to jazz music",
    "The train arrives at 5 pm",
    "She painted the walls blue",
    "We celebrated her birthday last weekend",
    "Can you speak more slowly please",
    "The river flows through the valley",
    "He fixed the broken chair",

    "Do you want to join us for dinner",
    "The stars shine brightly tonight",
    "She dances gracefully across the stage",
    "I lost my wallet yesterday",
    "They are planting trees in the park",
    "The movie was both funny and touching",
    "He enjoys playing chess with friends",
    "We should go for a run tomorrow",
    "Please send me the report by Monday",
    "The cat is sleeping on the sofa",

    "Learning new languages is exciting",
    "She baked cookies for the school event",
    "The kids are drawing pictures",
    "He repaired the car engine",
    "They watched a documentary about wildlife",
    "I love hiking during autumn",
    "The phone rang several times",
    "Can you open the window please",
    "She teaches mathematics at the university",
    "We went fishing last weekend",

    "The city lights sparkle at night",
    "He wrote a poem for his mother",
    "They are organizing a charity event",
    "I need to finish my homework",
    "The dog chased the ball",
    "She enjoys painting landscapes",
    "We had a picnic by the river",
    "Do you remember the password",
    "He bought a new bicycle",
    "They danced until midnight",

    "The chef prepared an exquisite dish",
    "I am planning a vacation next month",
    "She listens to classical music",
    "The garden is full of colorful flowers",
    "We visited the museum yesterday",
    "Can you recommend a good book",
    "He cleaned his room thoroughly",
    "They played soccer in the afternoon",
    "I received a letter from my friend",
    "The sunset painted the sky orange",

    "She studies biology at college",
    "We walked along the beach",
    "He fixed the leaking faucet",
    "Do you enjoy cooking new recipes",
    "The children built a sandcastle",
    "I am watching a documentary now",
    "They went shopping for groceries",
    "She wrote a novel last year",
    "We listened to the rain outside",
    "He jogs every morning",

    "The team won the championship",
    "I bought tickets for the concert",
    "She wears a beautiful dress",
    "They are learning to swim",
    "He gave a speech at the conference",
    "We ate dinner at a fancy restaurant",
    "The dog fetched the stick",
    "I like to read science fiction",
    "She opened the gift carefully",
    "They traveled by train to the city"
]

### Tokenize

In [37]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1

### Create input sequence

In [38]:
input_sequences = []
for line in corpus:
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i+1]
    input_sequences.append(n_gram_sequence)

### Pad sequences

In [39]:
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
print(input_sequences)

[[  0   0   0 ...   0   2   3]
 [  0   0   0 ...   2   3   1]
 [  0   0   0 ...   3   1  16]
 ...
 [  0   0   0 ...   7  38   1]
 [  0   0   0 ...  38   1   4]
 [  0   0  11 ...   1   4 100]]


### Split features and labels

In [40]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]
y = to_categorical(y, num_classes=total_words)

In [41]:
model = Sequential([
    Embedding(total_words, 10, input_length=max_sequence_len - 1),
    SimpleRNN(100),
    Dense(total_words, activation='softmax')
])

In [42]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.0749 - loss: 5.8882
Epoch 2/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1508 - loss: 4.9970
Epoch 3/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.1719 - loss: 4.7664
Epoch 4/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2400 - loss: 4.6865
Epoch 5/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2463 - loss: 4.5296
Epoch 6/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2493 - loss: 4.2756
Epoch 7/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2718 - loss: 3.9305
Epoch 8/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2795 - loss: 3.7776
Epoch 9/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3119 - loss: 3.5975
Epoch 10/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2933 - loss: 3.5957
Epoch 11/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3152 - loss: 3.4614
Epoch 12/500
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accura

In [44]:
def predict_next_word(seed_text):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len - 1, padding='pre')
    predicted_prob = model.predict(token_list, verbose=0)[0]
    predicted_index = np.argmax(predicted_prob)
    for word, index in tokenizer.word_index.items():
        if index == predicted_index:
            return word
    return ""

In [45]:
print(predict_next_word("I love to"))

play


In [46]:
print(predict_next_word("I love to watch"))

sports


In [47]:
print(predict_next_word("I love to eating"))

play


In [48]:
print(predict_next_word("I love to eat"))

salad


In [49]:
print(predict_next_word("I love to "))

play


In [50]:
def predict_next_word2(prefix):
    prefix = prefix.strip().lower()
    prefix_tokens = tokenizer.texts_to_sequences([prefix])[0]

    completions = set()
    for line in corpus:
        line_lower = line.lower()
        tokens = tokenizer.texts_to_sequences([line_lower])[0]
        # Check if line starts with prefix tokens
        if tokens[:len(prefix_tokens)] == prefix_tokens:
            # Get the remaining words after the prefix
            remaining_tokens = tokens[len(prefix_tokens):]
            if remaining_tokens:
                # Convert tokens back to words
                words_after_prefix = []
                for idx in remaining_tokens:
                    for word, index in tokenizer.word_index.items():
                        if index == idx:
                            words_after_prefix.append(word)
                            break
                # Join them with space and add '...' before it
                completion = '... ' + ' '.join(words_after_prefix)
                completions.add(completion)

    return list(completions)

print("Enter your phrase (type 'exit' to quit):")

while True:
    user_input = input("> ").strip()
    if user_input.lower() == 'exit':
        print("Goodbye!")
        break

    results = predict_next_word2(user_input)
    if not results:
        print("No suggestions found.")
        continue

    print("Suggestions:")
    for r in results:
        print("  " + r)


Enter your phrase (type 'exit' to quit):
> i love to
Suggestions:
  ... watch tv
  ... listen to the radio
  ... watch documentaries
  ... listen to electronic music
  ... travel abroad
  ... watch sports
  ... eat salad
  ... watch comedies
  ... play tennis
  ... cook vegan food
  ... exercise for fun
  ... read blogs
  ... play volleyball
  ... eat burger
  ... read articles
  ... cook desserts
  ... listen to classical music
  ... exercise to gain muscle
  ... relax on weekends
  ... exercise at the gym
  ... watch movies
  ... play football
  ... read comics
  ... play badminton
  ... learn coding
  ... play rugby
  ... cook fast food
  ... listen to jazz music
  ... relax in nature
  ... read stories
  ... eat sandwiches
  ... read poetry
  ... travel by train
  ... exercise daily
  ... learn cooking
  ... relax by the beach
  ... eat ice cream
  ... travel for adventure
  ... listen to rock music
  ... learn painting
  ... play chess
  ... travel by plane
  ... learn public spea