In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr[3]

4

There are 2 method we can create arrays using numpy

1. A list
2. A tuple

In [ ]:
a = ['MCA', 33, 54, 76, 99]
b = (1, 33, 54, 76, 99)

In [ ]:
arr1 = np.array(a)
arr2 = np.array(b)

In [ ]:
arr1

array(['MCA', '33', '54', '76', '99'], dtype='<U21')

In [ ]:
arr2

array([ 1, 33, 54, 76, 99])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
type(arr2)

numpy.ndarray

## Dimensions in arrays

1. 0-D Array
2. 1-D Array
3. 2-D Array
4. 3-D Array


In [ ]:
# 0 - D Array

print(np.array(33))

33


In [ ]:
# 1 - D Array

print(np.array([1, 2, 3, 4, 5]))

[1 2 3 4 5]


In [ ]:
# 2 - D Array

print(np.array([[1, 2, 3], [4, 5, 6]]))

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 - D Array

print(np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Assignments

1. Why we require Numpy? (Mention at least 4 points)
3. What is the difference between list, tuple, array?